### ISSUE TITLE
Wallet Generation website

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#190]

**Comment by schmidsi** [comment]
I repushed the original branch for the olympiad-placeholder wallet generation here: https://github.com/melonproject/melon-lab/tree/wallet-generation

I don't think that functionality changed since then, only styling. So one could safely:

```bash
git fetch origin
git checkout wallet-generation
rm -rf node_modules
yarn
cd packages/manager-interface
yarn dev
```

To develop and deploy like usual: Change the texts, etc.

**Comment by jennazenk** [comment]
https://registration.melonport.com/#/
