### ISSUE TITLE
Cannot read property logs of null

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#214]
Happened on trading to 2 different users although the transaction is successful
<img width="1005" alt="capture d ecran 2018-08-13 a 21 36 51" src="https://user-images.githubusercontent.com/17808182/44053811-142a0b8c-9f41-11e8-8601-b877ca2020a7.png">

**Comment by luongnt95** [comment]
the error might be caused by this https://github.com/melonproject/melon-lab/blob/master/packages/melon.js/lib/utils/parity/sendTransaction.js#L108 when the transaction is pending
