### ISSUE TITLE
Limit orders not visible on the Melon Interface Orderbook (Naxos)

### ISSUE THREAD

**Issue by agedubbs** [melonproject/melon-lab#216]
Step 1: I placed an sell order MLNWETH at the price of 0.03 (quantity: 10 MLNs)

Step 2: The order was placed (gas was paid) and it is visible under "Open Orders" and in my portfolio overview.

<img width="1185" alt="screen shot 2018-08-14 at 10 12 58" src="https://user-images.githubusercontent.com/31401984/44079944-cf5fdddc-9faa-11e8-976c-0801f1989599.png">

Step 3: The order is not shown on the Melon Interface Orderbook

<img width="792" alt="screen shot 2018-08-14 at 10 14 31" src="https://user-images.githubusercontent.com/31401984/44079960-dd6f90b6-9faa-11e8-83ba-2b9cc899d66c.png">

Step 4: In addition there are no "Recent Trades for MLNWETH

**Comment by jennazenk** [comment]
we will investigate why it is not shown in the orderbook. 

Regarding step 4 it is expected behavior that it wouldnt show under recent trades until the order is filled

**Comment by jennazenk** [comment]
Solved in getOrder the function isKnownAsset was causing that issue. Should be fine now. ALthough an order that was made "long time ago" might not be seen as on only fetch the 200 last orders
