### ISSUE TITLE
Link to my Ethereum address on registration.melonport.com is directed to kovan etherscan

### ISSUE THREAD

**Issue by agedubbs** [melonproject/melon-lab#217]
Step 1: I followed the steps and generated a wallet on registration.melonport.com

Step 2: To check my wallet I pressed on the address

<img width="434" alt="screen shot 2018-08-14 at 10 33 05" src="https://user-images.githubusercontent.com/31401984/44080808-7640d6e0-9fad-11e8-9f9a-a0e97b28376e.png">

Step 3: It re-directs me to https://kovan.etherscan.io/address/0x65787C6E2d3eF45592677D92adab70945B0Fb5c7

<img width="917" alt="screen shot 2018-08-14 at 10 33 49" src="https://user-images.githubusercontent.com/31401984/44080851-8e9a192c-9fad-11e8-8b6d-5a15b9ec1960.png">

**Comment by jennazenk** [comment]
link should be to etherscan.io/address/ADDRESS

**Comment by jennazenk** [comment]
for registration.melonport.com

**Comment by gempi** [comment]
@jennazenk it's fixed
