### ISSUE TITLE
Order book to list Volume in primary item in pairs

### ISSUE THREAD

**Issue by dragosid** [melonproject/melon-lab#223]
A suggestion I have (for something that's different than the rest of exchanges) is for a MLN/WETH pair to list in the Order Book the Volume for the 1st Asset (MLN in this case not the secondary)
As a trader you mainly need to know at a specified price (our case MLN) what volume is available... if it shows the WETH value it confuses things

**Comment by dragosid** [comment]
just realized now when comparing the order book with RadarRelay's one that on the Bid side it's displayed correctly (i.e Melon) where as on the Ask side it's displayed in WETH ....super confusing

![image](https://user-images.githubusercontent.com/42393285/44131728-f53cdf26-a065-11e8-83c6-1418d91c3ae6.png)
![image](https://user-images.githubusercontent.com/42393285/44131738-05355368-a066-11e8-9db6-77f940ce47b6.png)
![image](https://user-images.githubusercontent.com/42393285/44131781-41f7d6c2-a066-11e8-99be-d8cfd941aa67.png)

**Comment by jennazenk** [comment]
Thanks for pointing this out! Something got lost in a recent refactoring of that part. Fixed here: https://github.com/melonproject/melon-lab/commit/12a06fa18f9f9ff6d16e225954a9a1d0a69a6436

Will be included in upcoming release!

Regarding OasisDex, there is not much activity going on there, unless for orders placed by Melon Funds. When there is, you will see it as this orderbook aggregates them together with Radar Relay and ERCDex orders.
