### ISSUE TITLE
filling the order orice

### ISSUE THREAD

**Issue by dragosid** [melonproject/melon-lab#226]
any idea why clicking on the order book price (i.e I took the highest ask of 0.1) fills up the order price box with a different price (i.e: 0.0831)?

![image](https://user-images.githubusercontent.com/42393285/44124546-c70089ae-a03e-11e8-9912-58e82d861f8a.png)

**Comment by jennazenk** [comment]
Because it gives the average of the price of the order you selected + all the orders above
