### ISSUE TITLE
v0.8.3 - NAXOS "not connected to chain"

### ISSUE THREAD

**Issue by dirmansebastian** [melonproject/melon-lab#228]
melon desktop app doesn't connect anymore to chain :(

![image](https://user-images.githubusercontent.com/15945292/44145982-4798a25c-a096-11e8-86af-8f0c966f764b.png)

**Comment by jennazenk** [comment]
Did you download the latest version ? https://github.com/melonproject/melon-lab/releases/tag/v0.8.3

**Comment by dirmansebastian** [comment]
yeah, i did
![image](https://user-images.githubusercontent.com/15945292/44199365-8f62bf80-a14c-11e8-9dd9-ded54f8c8586.png)

**Comment by dirmansebastian** [comment]
it's windows 10, paros worked perfect with v0.8.1

**Comment by jennazenk** [comment]
When did you download the app ? There was a fix pushed a day and a half ago

**Comment by dirmansebastian** [comment]
i see there last release 3 days ago, https://github.com/melonproject/melon-lab/releases
on 14 i did, u pushed it on github?

**Comment by jennazenk** [comment]
I would recommend to re-download it and try again and let us know if you still have the issue

**Comment by dirmansebastian** [comment]
yupi, it worked :)
