### ISSUE TITLE
Error logging & tracking solution

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#253]
In order to learn about usage & bugs we should optionally log to a centralized service.

My suggestion is: 
- Use segment.com (we already have a test account there) to collect all data at a central place
- Distribute data from segment.com to Google Analytics & sentry.com (we already have accounts there)

What is to discuss is our general approach to data collection:
- We could say we just don't collect data at all. This would be bad for us because we would have a much harder time to debug and assist our users because we would be totally in the dark. Automated error logging with sentry is a huge help.
- My suggestion is to be sensible about it: Respect the Do-not-track flag on the web (https://github.com/melonproject/melon-lab/issues/74) and clearly communicate if we track or not. Give people that we track a subtle hint that it happens and that they could just turn on this flag. In electron: I'd suggest we make it opt-in on installation aka first start: Ask the user if they would like to share usage information with us.

To be further investigated: Regulatory requirements (GDPR and so on)

**Comment by jjperezaguinaga** [comment]
Chipping here as a complete outsider, but you might want to take a look at [Sentry](https://sentry.io) and [Rollbar](https://rollbar.com/). I've used both in the past, and both tackle GDPR (e.g. https://blog.sentry.io/2018/03/14/gdpr-sentry-and-you, https://rollbar.com/compliance/gdpr/), Sentry showcasing a more mature platform.

**Comment by schmidsi** [comment]
Thanks @jjperezaguinaga for the input. Actually, we already have a Sentry account and some services already log there but it needs an overhaul. I would also generally recommend Sentry over Rollbar. Used both of them and Sentry is more mature.

Didn't know about GDPR compliance. Thanks for pointing at this.
