### ISSUE TITLE
Subscription for balance

### ISSUE THREAD

**Issue by fundboy** [melonproject/melon-lab#279]
Hi everyone. 
Sorry to post that issue here but not see any other possiblity. 

Independent of the amount which I get from faucet, the page still shows all the time "Insufficient ETH Balance". How to go forward here? Is there any other documentation available instead of the tecnical one? That behavior also don't match the "Setting up a Melon fund DEMO" video on youtube. 

hope you can write a short answer or maybe refer to a user group or something simillar. If there is no one available I would be happy to organizse one. I'm very interested to do some tests and also to start own funds in the near future. 

However. You do a great job to implement that framework and I'm sure it will change a lot our world in the near future. 

Best regards
Alex

**Comment by jennazenk** [comment]
hey @fundboy thanks for filing an issue here. The version you are trying to use is now deprecated and we don't maintain it anymore as we are working toward the v1 release, which should happen by end of February. I am sorry for the inconvenience, but what this means is that you'll be able to setup a fund on the testnet or on the main net in just a few weeks, with the latest version of the interface! I can ping you here when it's ready :)

**Comment by schmidsi** [comment]
This only works with websockets which we will be using in v1.0
