### ISSUE TITLE
Invest in an already running fund

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#283]
A second invest is currently not possible. We need to create a solution with the waiting period.

- [x] getRequest query (incl. if it is valid or not) (Simon)
- [x] Waiting/execute screen (Matt)
- [x] Separate execute request transaction (Matt)

**Comment by jennazenk** [comment]
Not possible in UI you mean?

At smart contract level it's possible. 

Idea: when a user goes on a fund page, call `getRequest` to see if the user has an open request
- if no request, give the option to `requestInvestment` (in assets that are enabled)
- if there is a request,  call `hasValidRequest` to see if if he can execute the request. If he can execute it, give the option to `executeRequest`. If he can't execute it, maybe display when it will be executable, or if it needs to be canceled

**Comment by schmidsi** [comment]
Cancel in #292
