### ISSUE TITLE
import json wallet + type password does nothing 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#300]
<img width="1413" alt="capture d ecran 2019-02-13 a 12 52 59" src="https://user-images.githubusercontent.com/17808182/52709931-5d60d780-2f8e-11e9-85e8-6ef08fdaca5e.png">

**Comment by schmidsi** [comment]
With wrong password, the error message gets swallowed:

```
index.js:2178 [GQL ERROR]: Message: invalid password, Path: importWallet, Locations: [{…}]
```

Should display somewhere
