### ISSUE TITLE
Deploying multiple policies causes slice error

### ISSUE THREAD

**Issue by travs** [melonproject/melon-lab#304]
It seems to occur with whatever policy I select last actually, regardless of the policy type.
And it is during deployment, instead of registration.

~~On devchain, also have other policies active when I do this, but they deploy fine.
Also happens with one asset on the list.
Also happens with `assetBlacklist` (multiple assets), and `userWhitelist`, with one address (manager's), and maxConcentration (12%).~~

https://imgur.com/a/M4OeaDt

**Comment by jennazenk** [comment]
additionally, on the main net, trying to register 4 or 5 policies result in 0 policies actually registered. Trying to reproduce this again. 

See this `batchRegister()`tx with empty input: https://etherscan.io/tx/0x4986dcb2d2896f23767272ce7d6c21390a4a7d0d6b39f9b5fa2be5af3aa636e9
