### ISSUE TITLE
Gas Error when redeeming

### ISSUE THREAD

**Issue by solarcurve1** [melonproject/melon-lab#306]
When I go to redeem in my fund then enter any share amount, I get the following error:

GraphQL error: Error in prepare transaction Participation@0x2c8ae79dc9046207EDCAd7Bbf6e5DA368b59EaDA.redeemQuantity("1000000000000000000")): Gas estimation (preflight) failed for redeemQuantity("1000000000000000000"): Returned error: gas required exceeds allowance or always failing transaction

Note that I shutdown the fund prior to trying to redeem.

**Comment by jennazenk** [comment]
Hey @solarcurve1 , you were still not able to redeem your shares?

**Comment by solarcurve1** [comment]
Yes, still can't redeem. Tried on another computer and got the same error.

When I hit view on etherscan inside melon, this address comes up. https://etherscan.io/address/0xc4c4d9f08492F15DeA16bEE608A83A8aa46C7aC4

**Comment by housemobile** [comment]
Same error for me.

GraphQL error: Error in prepare transaction Participation@0x7D7463F21f6AEA3318a20ed0002E2C6b3E64C143.redeemQuantity("1000000000000000000")): Gas estimation (preflight) failed for redeemQuantity("1000000000000000000"): Returned error: gas required exceeds allowance or always failing transaction

**Comment by housemobile** [comment]
Fund address: 0x2d5457D718840eBa7760e384A5177401A9410848

**Comment by housemobile** [comment]
Note: I did not shutdown the fund. I am simply trying to redeem some of my shares.

Windows 10.

0.187951 ETH balance.

**Comment by JakeBarclay** [comment]
I'm receiving the same error but for executeRequest. On windows and linux.

**Comment by farmer9** [comment]
I get this same error when attempting to make a limit order.

`GraphQL error: Error in prepare transaction Trading@0xb7ace227f15250FB67B30286f17A24DffECf5f83.callOnExchange(1,"makeOrder(address,address[6],uint256[8],bytes32,bytes,bytes,bytes)",["0xb7ace227f15250FB67B30286f17A24DffECf5f83","0x0000000000000000000000000000000000000000","0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],["50000000000000000","362000000000000","0","0","0","0","0",0],"0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000")): Gas estimation (preflight) failed for callOnExchange(1, "makeOrder(address,address[6],uint256[8],bytes32,bytes,bytes,bytes)", ["0xb7ace227f15250FB67B30286f17A24DffECf5f83","0x0000000000000000000000000000000000000000","0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"], ["50000000000000000","362000000000000","0","0","0","0","0",0], "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"): Returned error: gas required exceeds allowance or always failing transaction`

**Comment by lukue** [comment]
I also shutted down my fund in v.1.0.0 and now tried to redeem in v1.0.0 and v1.0.0patched. Have the same error as solarcurve1.

**Comment by jennazenk** [comment]
@solarcurve1 @housemobile  sent you instructions to redeem on email/@jatelegram. 
@lukue do you still have the issue? If so, can you give me the address of your fund, and I'll send you instructions as well: jenna@melonport.com
@farmer9 @JakeBarclay although the error message look similar these are different issue, can you open it in a separate issues?
