### ISSUE TITLE
Error after an attempt to setup the fund

### ISSUE THREAD

**Issue by Mylittlerapture** [melonproject/melon-lab#307]
I was trying to setup the fund and got this error:

`GraphQL error: Error in prepare transaction FundFactory@0xCB6c6Bdf0AA4cF0188518783b871931EFB64248f.beginSetup("0x00000000000000000000000000000000000000000000414c5048412046554e44",["0x67d8f29c6956e591bc43c0dcc82b87d6a6eb76e7","0xcc44fcfe13d4aec61f1835fb5f8ae7ebe06d42cd"],["13000000000000000","130000000000000000"],["0","2592000"],["0x4f833a24e1f95d70f028921e27040ca56e09ab0b","0x39755357759cE0d7f32dC8dC45414CCa409AE24e","0x818E6FECD516Ecc3849DAf6845e3EC868087B755","0x7CaEc96607c5c7190d63B5A650E7CE34472352f5"],["0x9312D09433fFF34f7b57b02996486d54D420eA74","0x542F91538205FCe34c7e1538b7Ce2218655D8623","0x8CB3E810027d97BE5E890257338b9Cc755dE9c67","0xF31D358eFD7B80A6733BCb850bd49BFCBEC1428A"],"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0xec67005c4e498ec7f55e092bd1d35cbc47c91892","0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"],[false,true,false,false])): Gas estimation (preflight) failed for beginSetup("0x00000000000000000000000000000000000000000000414c5048412046554e44", ["0x67d8f29c6956e591bc43c0dcc82b87d6a6eb76e7","0xcc44fcfe13d4aec61f1835fb5f8ae7ebe06d42cd"], ["13000000000000000","130000000000000000"], ["0","2592000"], ["0x4f833a24e1f95d70f028921e27040ca56e09ab0b","0x39755357759cE0d7f32dC8dC45414CCa409AE24e","0x818E6FECD516Ecc3849DAf6845e3EC868087B755","0x7CaEc96607c5c7190d63B5A650E7CE34472352f5"], ["0x9312D09433fFF34f7b57b02996486d54D420eA74","0x542F91538205FCe34c7e1538b7Ce2218655D8623","0x8CB3E810027d97BE5E890257338b9Cc755dE9c67","0xF31D358eFD7B80A6733BCb850bd49BFCBEC1428A"], "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", ["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0xec67005c4e498ec7f55e092bd1d35cbc47c91892","0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"], [false,true,false,false]): Returned error: gas required exceeds allowance or always failing transaction`

After I got the error neither Cancel nor Confirm button was responsive. One of the reason might be that i left gas price as 5 but at Gas Station it was shown that it's more than enough.

![err](https://user-images.githubusercontent.com/14307880/53718379-1585ef80-3e6c-11e9-93a4-5d27ca47cd5e.png)

**Comment by johanneskern** [comment]
![image](https://user-images.githubusercontent.com/11295272/53737493-f8ade400-3e8c-11e9-92fe-8f534eb118cc.png)
I don't know if this is the same error or a different one...

**Comment by Mylittlerapture** [comment]
Eventually I was able to setup the fund. But It threw similar errors at few first steps, so i'm not sure if everything went fine.

And now after I tried to invest in it, this is what I get at executeRequest step: 
![err](https://user-images.githubusercontent.com/14307880/53741150-c9a46c00-3ea6-11e9-8f4e-8106eab350a5.png)

**Comment by jennazenk** [comment]
hey @Mylittlerapture thanks for the report. It seems that the pricesource might have been a bit down while you were creating your fund (assumption). What's your OS?

**Comment by Mylittlerapture** [comment]
Windows 10. It throws exact same error as above. Might it be the case that I left too small amount of eth on my wallet? What operation cost of executeRequest should be?

**Comment by Mylittlerapture** [comment]
The issue is resolved. Thank you for help Jenna.
