### ISSUE TITLE
Oasis (eth2dai) limit order on old contract

### ISSUE THREAD

**Issue by farmer9** [melonproject/melon-lab#322]
![Screenshot from 2019-03-15 16-58-40](https://user-images.githubusercontent.com/46238156/54464221-c41b1180-4743-11e9-89a0-def68afebc6a.png)
0xB7ac09C2c0217B07d7c103029B4918a2C401eeCB is the old oasis contract. This needs to be updated to the new contract 0x39755357759cE0d7f32dC8dC45414CCa409AE24e

**Comment by jennazenk** [comment]
hey thanks for reaching out. 0xB7ac09C2c0217B07d7c103029B4918a2C401eeCB  is the address of your trading contract, not OasisDex (they just start very similarly). The OasisDex address that we use is indeed 0x39755357759cE0d7f32dC8dC45414CCa409AE24e

**Comment by farmer9** [comment]
Ahh, I see. I only looked at the first 4 characters. This can be closed.
