### ISSUE TITLE
Add returnBatchToVault step before redeem is called 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#325]
conditional to: 

- there is no open order 
- therer are assets in the trading component (instead of the vault component) 

This call to `returnBatchToVault()` (on the Trading contract) must be done before calling `redeem`

**Comment by iherger** [comment]
We should also add a button to call `returnBatchToVault()` the frontend condional on:

- assets in the trading contract
- open order is expired

**Comment by jennazenk** [comment]
addressed in v1.0.2
