### ISSUE TITLE
Error when trying to invest weth into a newly created fund

### ISSUE THREAD

**Issue by atrashko** [melonproject/melon-lab#327]
Error when trying to invest weth into a newly created fund (not owned by the investor address)  (on a Mac): GraphQL error: Error in prepare transaction Participation@0xFDEE51e9B79A9159d7023BD6e8f537aF17E4be32.requestInvestment("1200000000000000000","1200000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2")): Gas estimation (preflight) failed for requestInvestment("1200000000000000000", "1200000000000000000", "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"): Returned error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type *hexutil.Big
![Screen Shot 2019-06-02 at 20 08 36](https://user-images.githubusercontent.com/51297274/58765392-f5e98a80-8572-11e9-9931-8c813a733903.png)

**Comment by MouyouMoos** [comment]
it went through https://etherscan.io/tx/0x0af087c1b9f04b63068ec2301bace39fdd1012f4b55fdd291c809012a25ee96e
