### ISSUE TITLE
Error message when trying to sell asset

### ISSUE THREAD

**Issue by atrashko** [melonproject/melon-lab#328]
Melon Manager (Mac version) says there are no funds to sell (buy trade was 1-2 days ago). Melon Network website shows funds for that coin (MKR) as part of the fund's assets.

![Screen Shot 2019-06-04 at 11 30 52](https://user-images.githubusercontent.com/51297274/58868465-b2029c80-86bc-11e9-8461-bd79c09ce59f.png)
![Screen Shot 2019-06-04 at 11 31 13](https://user-images.githubusercontent.com/51297274/58868466-b2029c80-86bc-11e9-8946-844233e3b6c5.png)

**Comment by iherger** [comment]
This is due to the fact the the assets are in the Trading contract and not in the Vault contract. The solution for #325 will fix this.

**Comment by jennazenk** [comment]
addressed in v1.0.2
