### ISSUE TITLE
Decimal issue on orderbook with tokens having something different than 18 dec 

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/melon-lab#336]
Effecting all Kyber order books - I know @fubhy & G already looking at this but logging the issue here to keep track.
<img width="531" alt="Screenshot 2019-06-28 at 11 06 25" src="https://user-images.githubusercontent.com/20302429/60331452-01bf4580-9995-11e9-9a78-b2c1ad36437d.png">

**Comment by jennazenk** [comment]
this might not be just token math related. Renaming issue

**Comment by jennazenk** [comment]
addressed in v1.0.2
