### ISSUE TITLE
Misleading warning after successfully submitting investment request 

### ISSUE THREAD

**Issue by iherger** [melonproject/melon-lab#339]
After a successful submission of an investment request, a warning message says 
```You already have a pending investment request in this fund. You will be able to execute that request between the next pricefeed update and 24 hours from now.```

Screenshot:
<img width="947" alt="Screenshot 2019-07-04 at 14 02 49" src="https://user-images.githubusercontent.com/36133712/60665319-7518f980-9e64-11e9-8080-cbbdc226a7cf.png">

This warning should only be displayed when an investor tries to invest into a fund where they have already place an investment request, and not in the case where the investment request was successfully submitted.

After the successful submission of an investment request, there should be a note along the lines of 
```You have successfully submitted your investment request in this fund. You will have to execute that request between the next pricefeed update and 24 hours from now.```

(Side note: just before submitting the successful investment request, I had successfully cancelled an expired investment request)

**Comment by jennazenk** [comment]
Closing as this was addressed in v1.0.2
