### ISSUE TITLE
New fund <> unauthorized GWEI deduction from my balance

### ISSUE THREAD

**Issue by xirkle** [melonproject/melon-lab#345]
Hi,

I'm trying to create a new fund, but it wasn't successful. I got an error message and Melon deducted GWEI from my account. Why did Melon deducted a transaction fee if it wasn't successful?!

Please advise. Thanks.

Here's the transaction: https://etherscan.io/tx/0xf4547d53d81df649f7b23e1742ee50eeedff87e81ae68deeb063ca629968aeff

Screenshot:

![image](https://user-images.githubusercontent.com/30379932/61592243-c3d1cd80-ab9e-11e9-94a8-02ac6ca98a80.png)

**Comment by xirkle** [comment]
I just tried to create another new fund and it error out again.

![image](https://user-images.githubusercontent.com/30379932/61592263-1612ee80-ab9f-11e9-99ce-4b7387f3a55f.png)

**Comment by iherger** [comment]
Hi @xirkle 

Thanks for reporting the issue.

My first guess would be that you may not have enough ETH in your manager account to pay for the creation of the fund (you need to pay gas and amgu).

The address you linked to, `0xe712C626210DE71AE86bb43b3436360fd231cE12` (which I assume is your manager address) contains only 0.01 ETH, which is not enough to set up a fund, https://etherscan.io/address/0xe712c626210de71ae86bb43b3436360fd231ce12

In addition, it seems that you are using an older version of the melon manager interface, using the old `version` contract `0xcb6c6bdf0aa4cf0188518783b871931efb64248f`. The latest version of the melon manager interface is using the `version` contract `0x01bde0b02740d6311e4a87ca112deeeddb057efb`. If that's the case, please download the latest version of the melon manager interface (v. 1.0.2) from https://github.com/melonproject/melon-lab/releases

**Comment by iherger** [comment]
Also, it's important to understand that the fund setup process consists of a total of **nine** steps . You (as the fund manager) have to approve every single step. For every step, you pay gas and the melon engine charges amgu (asset management gas units) for the operation of the melon network. There is never any unauthorised deduction of GWEI from your account.
