### ISSUE TITLE
Errors w/ fund wind down

### ISSUE THREAD

**Issue by hjhettich** [melonproject/melon-lab#347]
FundContract: 0xB980e1857d4dd17DeF4707E03bF7632f5dd95c92

Fund still shows an Open Limit Order, however, this order is very old, not visible on any DEX or the aggregated order book and is to buy MLN at 0.05 WETH (again, it’s an old order and would have been executed in the meantime).

Error Message when CancelOrder: 
GraphQL error: Call failed. PreminedToken@0x0000000000000000000000000000000000000000.totalSupply(): Returned values aren't valid, did it run Out of Gas?

Executed FundShutDown. Fund is shutdown now.

Error Message when ClaimRewards:
GraphQL error: Error in prepare transaction Accounting@0x3fc35Fe6efaEB8375B6F76c7260708459A90e0B5.triggerRewardAllFees()): Gas estimation (preflight) failed for triggerRewardAllFees(): Returned error: gas required exceeds allowance or always failing transaction

Investor also can’t redeem its shares and hasn’t received back its investment.

**Comment by iherger** [comment]
Your fund seems to still have assets in the Trading contract, which haven't been moved to the Vault contract.

Can you try moving the assets to the Vault contract first? The latest version of the melon manager interface has a "release" button, which will "release" the assets in the Trading contract into the Vault contract. After that, redemption should be possible.

**Comment by hjhettich** [comment]
Gotcha, thanks! Release and redemption worked. 

Still error message with "claim rewards" as manager:
GraphQL error: Error in prepare transaction Accounting@0x3fc35Fe6efaEB8375B6F76c7260708459A90e0B5.triggerRewardAllFees()): Gas estimation (preflight) failed for triggerRewardAllFees(): Returned error: gas required exceeds allowance or always failing transaction

**Comment by iherger** [comment]
As far as I can see, the fees have been transferred to the manager, i.e. "Claim Rewards" has been successful. 

You should be able to redeem the outstanding 0.002623805600575771 shares of the manager.

**Comment by hjhettich** [comment]
That's it... redeem the earned shares. Worked all fine. Problem solved. Thank you!
