### ISSUE TITLE
Error when confirming fund creation

### ISSUE THREAD

**Issue by Codonyat** [melonproject/melon-lab#348]
See error message:
`GraphQL error: Error in prepare transaction FundFactory@0x575fBB8029a10545cccC3c0EB6Da8EE3f8b0a022.beginSetup("0x0000000000000000000000000000000000000000000000000000000000547279",["0xe9d49808967d574f7aec6a5fe11766d01819c6c7","0xbb7e55a9199191501dbfbc68862f5e93bc370827"],["0","200000000000000000"],["0","7776000"],["0x35dd2932454449b14cee11a94d3674a936d5d7b2","0xbED692938E714Da2a1d5407E5D99658F7D4c8079","0x7e6b8b9510D71BF8EF0f893902EbB9C865eEF4Df","0xeEDE875Bdc389629eA4E30f0A5fF309a4E5aFF4C"],["0xA28e3301222B9cb9C54910F0620Fbf92bbE38be3","0xA27CB53BdBbb12d21E8e28aa84e2486c52A89663","0xA1A4aD89C376Cab1731d06b4680B13d3B9340278","0x24289D3dee1c6eA31bEe75d8A7Dd6a36E29F26c6"],"0xd0A1E359811322d97991E03f863a0C30C2cF029C",["0xd0a1e359811322d97991e03f863a0c30c2cf029c","0xa80C98433E2a82DF3636ED934083E3285163Fad8","0x0A3610a0E87cEDDEE6b81b62b462c7a0fD450E2a","0x2C2edf394638931eb672BD9261d2AA1934874d45","0xbdaD7a926A7E70C6B0AF367d97D992b904BBAFcf","0x1D3bC44DD6C3F00640A6825B48F1C78770fd21d8"])): Gas estimation (preflight) failed for beginSetup("0x0000000000000000000000000000000000000000000000000000000000547279", ["0xe9d49808967d574f7aec6a5fe11766d01819c6c7","0xbb7e55a9199191501dbfbc68862f5e93bc370827"], ["0","200000000000000000"], ["0","7776000"], ["0x35dd2932454449b14cee11a94d3674a936d5d7b2","0xbED692938E714Da2a1d5407E5D99658F7D4c8079","0x7e6b8b9510D71BF8EF0f893902EbB9C865eEF4Df","0xeEDE875Bdc389629eA4E30f0A5fF309a4E5aFF4C"], ["0xA28e3301222B9cb9C54910F0620Fbf92bbE38be3","0xA27CB53BdBbb12d21E8e28aa84e2486c52A89663","0xA1A4aD89C376Cab1731d06b4680B13d3B9340278","0x24289D3dee1c6eA31bEe75d8A7Dd6a36E29F26c6"], "0xd0A1E359811322d97991E03f863a0C30C2cF029C", ["0xd0a1e359811322d97991e03f863a0c30c2cf029c","0xa80C98433E2a82DF3636ED934083E3285163Fad8","0x0A3610a0E87cEDDEE6b81b62b462c7a0fD450E2a","0x2C2edf394638931eb672BD9261d2AA1934874d45","0xbdaD7a926A7E70C6B0AF367d97D992b904BBAFcf","0x1D3bC44DD6C3F00640A6825B48F1C78770fd21d8"]): Returned error: The execution failed due to an exception.`

**Comment by jennazenk** [comment]
Hello, it seems your wallet address does not have enough ether to create a fund. In order to create a fund, you need ether to pay for ethereum and melon gas. I'd recommend having 0.1-0.2 ether in your wallet

**Comment by Codonyat** [comment]
Hi Jenna,

I have almost 1eth in Kovan where I am testing the fund.

Missatge de Jenna Zenk <notifications@github.com> del dia dv., 26 de jul.
2019 a les 11:04:

**Comment by Codonyat** [comment]
Screenshot just right before I get the error message.
[image: image.png]

Missatge de Nil Garcia <nil.garcia@gmail.com> del dia dv., 26 de jul. 2019
a les 22:15:
