### ISSUE TITLE
I can't finish configuring my fund

### ISSUE THREAD

**Issue by claveros** [melonproject/melon-lab#355]
my fund is called Marce
![image](https://user-images.githubusercontent.com/34797483/66832940-8e513c00-ef63-11e9-9250-7d590b076d4b.png)

**Comment by jennazenk** [comment]
It seems the fund has been fully configured and invested in it though: https://monitoring.melon.network/fund?address=0xe157c1e7b279605026663e0401b059fbe8a3d8c3

Please reopen if that's not the case.
