### ISSUE TITLE
Brave browser retains the seed phrase as auto fill when restoring by typing phrase.

### ISSUE THREAD

**Issue by john-0x** [melonproject/melon-lab#58]
In Brave on olympiad.melon.fund.  Perhaps this is also the case for other browsers. This is likely not the desired behavior.

**Comment by schmidsi** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by schmidsi** [comment]
There is only the Electron release. So we can close this.
