### ISSUE TITLE
Orderbook styling 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#69]
As we expect more liquidity on the exchange aggregator during olympiads, we need to decide on a way to make the orderbook look nice: 

<img width="1057" alt="capture d ecran 2018-06-14 a 11 50 32" src="https://user-images.githubusercontent.com/17808182/41405136-4f159344-6fc9-11e8-8fc1-acd001b9b9a1.png">

**Comment by schmidsi** [comment]
We cannot find the perfect solution, but we can:
- Remove the lines
- Smaller padding
- Smaller font-size
- Limit table. I.e. Only display 20 or so orders on each side but clearly state that there are more. I think users are mostly interested in the top orders (?)

Maybe @gempi has also some ideas?

**Comment by schmidsi** [comment]
Perfect solution comes with redesign
