### ISSUE TITLE
Isolate yarn workspace packages in docker builds

### ISSUE THREAD

**Issue by fubhy** [melonproject/melon-lab#89]
Currently, our production per-service docker images are larger than they need to be due to the yarn workspace environment. Lately, (v1.7.0) yarn introduced a "--focus" option to install packages within a workspace in isolation. We should use that to isolate our services in production. Currently, however, this is not possible because it requires local dependencies to  be published, which we can't and won't do because some of them are merely private utilities that we don't want to have in the npm registry. And even if we wanted to have them in the registry, we wouldn't want to publish them during the build (e.g. think about feature branches, etc.). It would result in a chicken and egg problem because we would have to first build the whole workspace, run the tests, etc. then publish them and then build the isolated images AGAIN (now, downloading the local dependencies from npm). There is an open issue on the yarn project also discussing this scenario: https://github.com/yarnpkg/yarn/issues/4521

**Comment by schmidsi** [comment]
I don't see a problem with publishing all the packages. We can opt for alpha versions. E.g. 0.8.5-alpha.5.

How often would this happen?
