### ISSUE TITLE
Get fund trade history also on 0x exchanges

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#97]
It seems like getRecentTrades and getFundRecentTrades only queries MatchingMarket.

Probably getOrdersHistory gets also the ones from 0x, but this is to check.

**Comment by jennazenk** [comment]
Right - checked for getOrdersHistory it is there. 

For getRecentTrades (which is exchange recent trades), we only get recent trades related to OasisDex. 

If we want those on 0x, we need either to find an API that provides that, or to look for `LogFill` events on the 0x contract for the given asset pair (might be ressources intensive if done for every client)

 https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/src/contracts/current/protocol/Exchange/Exchange.sol#L200-L212

**Comment by schmidsi** [comment]
Duplicate of #186 
Will be addressed in https://github.com/melonproject/exchange-aggregator/issues/3
